// src/components/ResponsePill.tsx
import clsx from 'clsx';
import { Response } from '../types';

export default function ResponsePill({ questionId, responses }: { questionId: string, responses: Response[] }) {
  const response = responses.find(r => r.question_id === questionId);
  let text = ''
  if (response?.value) {
    text = response.value
  } else {
    text = 'null'
  }
  const formatted = !text ? null : text.split('_').map(word => `${word.charAt(0).toUpperCase()}${word.slice(1)}`).join(' ')
  let colors = ''
  switch (text) {
    case 'yes':
      colors = 'bg-emerald-100 text-emerald-800'
      break;
    case 'no':
      colors = 'bg-red-100 text-red-800'
      break;
    case 'if_needed':
      colors = 'bg-yellow-100 text-yellow-800'
      break;
    default:
      colors = 'bg-gray-100 text-gray-800'
  }

  return (<span className={clsx("inline-flex items-center px-3 py-0.5 rounded-full text-sm font-medium", colors)}>{formatted}</span>)
}

// src/components/ResponsePill.vue
<template>
    <span class="inline-flex items-center px-3 py-0.5 rounded-full text-sm font-medium" :class="colors" v-show="formatted">
        {{ formatted }}
    </span>
</template>

<script>
export default {
    name: 'ResponsePill',
    props: {
        text: {
            type: String,
            default: ''
        }
    },
    computed: {
        formatted() {
            if (!this.text) return null
            return this.text.split('_').map(word => `${word.charAt(0).toUpperCase()}${word.slice(1)}`).join(' ')
        },
        colors() {
            if (this.text === 'yes') {
                return 'bg-emerald-100 text-emerald-800'
            } else if (this.text === 'no') {
                return 'bg-red-100 text-red-800'
            } else if (this.text === 'if_needed') {
                return 'bg-yellow-100 text-yellow-800'
            } else {
                return 'bg-gray-100 text-gray-800'
            }
        }
    },
}
</script>
