// src/components/AppHeader.tsx
import { Link } from '@tanstack/react-router'
import AppMenu from './AppMenu';
import { useAuth } from '../auth';

export default function AppHeader() {
  const { user } = useAuth();
  
  return (
    <header className="bg-blue-600 shadow-sm">
      <div className="w-full max-w-7xl mx-auto py-6 px-4 sm:px-6 lg:px-8 flex justify-between items-center">
        <h1 className="text-2xl leading-6 font-bold text-white">
          <Link to="/" className="hover:opacity-90">McDoodle</Link>
        </h1>
        <div>
          {user ? (<AppMenu />) : (
          <Link to="/login" className="inline-flex w-full justify-center rounded-md bg-black/20 px-3 py-1.5 text-sm font-medium text-white hover:bg-black/30 focus:outline-none focus-visible:ring-2 focus-visible:ring-white/75">Sign In</Link>
          )}
        </div>
      </div>
    </header>
  );
}

// old/src/components/AppHeader.vue
<template>
    <header class="bg-blue-600 shadow-sm">
        <div class="max-w-7xl mx-auto py-6 px-4 sm:px-6 lg:px-8">
            <h1 class="text-2xl leading-6 font-bold text-white"><router-link to="/" class="hover:opacity-90">McDoodle</router-link></h1>
        </div>
    </header>
</template>

<script>
export default {
    name: 'AppHeader'
}
</script>
